data:
  data_dir: /home/ibm2024/jittor/starter_code/starter_code
  dataset: StarterLocal
  augment: false
  use_rgb_features: false
  workers: 2
  npoints: 2048
  train_split: train
  val_split: local_val
  dense_size: 50000
  noise_min: 0.005
  noise_max: 0.020
  train_patches_per_cloud: 200
  val_patches_per_cloud: 4
diffusion:
  timesteps: 1000
  sampling_timesteps: 10
  objective: pred_noise
  schedule: linear
  sampling_strategy: DDPM
  loss_type: rodr
  rodr_tangent_weight: 1.0
  beta_start: 1.e-4
  beta_end: 0.02
  t0: 1.e-4
  T: 1.0
  ot_ode: true
model:
  type: PVD
  ema: true
  in_dim: 3
  extra_feature_channels: 0
  out_dim: 3
  time_embed_dim: 64
  dropout: 0.15
  EMA:
    decay: 0.999
  PVD:
    use_global_embedding: true
    global_embedding_dim: 1024
    feat_embed_dim: 32
    attention_type: linear
    attention_heads: 4
    size: large
    attentions:
    - 0
    - 0
    - 0
    - 1
    channels:
    - 32
    - 64
    - 128
    - 256
    - 512
    voxel_resolutions:
    - 32
    - 16
    - 8
    - 8
    n_sa_blocks:
    - 1
    - 2
    - 1
    - 1
    n_fp_blocks:
    - 1
    - 2
    - 1
    - 1
    radius:
    - 0.1
    - 0.2
    - 0.4
    - 0.8
    out_mlp: 128
training:
  optimizer:
    type: AdamW
    lr: 3.e-4
    beta1: 0.9
    beta2: 0.999
    weight_decay: 1.0e-05
  scheduler:
    type: constant
    lr_gamma: 0.999
  grad_clip:
    enabled: true
    value: 1.0
  bs: 8
  overfit: false
  amp: true
  steps: 2000
  accumulation_steps: 1
  log_interval: 10
  save_interval: 1000
  viz_interval: 1000
  seed: 42
sampling:
  bs: 8
  num_iter: 8
  accum_iter: 4
